# Generated by Django 5.0.1 on 2025-11-23 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_historiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquemodel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_historiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_historiques', to=settings.AUTH_USER_MODEL),
        ),
    ]
