# Generated by Django 5.0.1 on 2025-11-23 20:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('max_apps', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_executions_per_24h', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'licenses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='licenses_tenant__855b76_idx'), models.Index(fields=['valid_from', 'valid_to'], name='licenses_valid_f_e32dd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenseUpgrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_max_apps', models.IntegerField()),
                ('previous_max_executions', models.IntegerField()),
                ('previous_valid_to', models.DateTimeField()),
                ('new_max_apps', models.IntegerField()),
                ('new_max_executions', models.IntegerField()),
                ('new_valid_to', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='licenses.license')),
            ],
            options={
                'db_table': 'license_upgrades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('performed_by', models.CharField(max_length=255)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='licenses.license')),
            ],
            options={
                'db_table': 'license_history',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['license', 'performed_at'], name='license_his_license_685314_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenseToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='licenses.license')),
            ],
            options={
                'db_table': 'license_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license', 'is_active'], name='license_tok_license_f53c47_idx'), models.Index(fields=['expires_at'], name='license_tok_expires_d8a5bd_idx')],
            },
        ),
    ]
