# Generated by Django 5.0.1 on 2025-11-23 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='licenses.license')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_jobs', models.IntegerField(default=0)),
                ('successful_jobs', models.IntegerField(default=0)),
                ('failed_jobs', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('avg_execution_time', models.FloatField(default=0)),
                ('max_execution_time', models.FloatField(default=0)),
                ('min_execution_time', models.FloatField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='applications.application')),
            ],
            options={
                'db_table': 'application_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['license', 'is_active'], name='application_license_3a571e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['api_key'], name='application_api_key_0c804e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('license', 'name')},
        ),
        migrations.AddIndex(
            model_name='applicationmetrics',
            index=models.Index(fields=['application', 'date'], name='application_applica_33f518_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationmetrics',
            unique_together={('application', 'date', 'hour')},
        ),
    ]
