# Generated by Django 5.0.1 on 2025-11-23 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='applications.application')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='licenses.license')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_record', to='jobs.job')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='licenses.license')),
            ],
            options={
                'db_table': 'job_executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_processing', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='jobs.job')),
            ],
            options={
                'db_table': 'job_queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['application', 'status'], name='jobs_applica_32e4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['license', 'started_at'], name='jobs_license_74ab4c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['started_at'], name='jobs_started_95abd0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_status_92f544_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecution',
            index=models.Index(fields=['license', 'executed_at'], name='job_executi_license_2e6afc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecution',
            index=models.Index(fields=['tenant_id', 'executed_at'], name='job_executi_tenant__df3ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecution',
            index=models.Index(fields=['executed_at'], name='job_executi_execute_7b7ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobqueue',
            index=models.Index(fields=['is_processing', 'priority'], name='job_queue_is_proc_7efb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobqueue',
            index=models.Index(fields=['scheduled_at'], name='job_queue_schedul_9d106b_idx'),
        ),
    ]
